[project]
name = "macronome"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.120.1",
    "litellm>=1.79.0",
    "marimo>=0.17.2",
    "mlflow>=3.1.4",
    "pillow>=11.3.0",
    "ultralytics>=8.3.221",
]
